Refactoring: Timestamps
stroeer/tapir pull request #160
Opened 2021-02-15 10:45 UTC by bobaaaaa

From the FE perspective we only need two dates:

* publication date
* updated (Aktualisiert am)

Let's discuss!

2021-02-15 12:08 UTC, thisismana approved these changes
this is fine.

2021-02-15 12:19 UTC, thisismana requested changes

2021-02-15 12:19 UTC, thisismana commented on stroeer/core/v1/article.proto
> +  google.protobuf.Timestamp published = 4;
```suggestion
  google.protobuf.Timestamp publish_time = 4;
```

2021-02-15 12:19 UTC, thisismana commented on stroeer/core/v1/article.proto
> +  google.protobuf.Timestamp updated = 5;
```suggestion
  google.protobuf.Timestamp update_time = 5;
```

2021-02-16 11:03 UTC, moritzzimmer requested changes
@bobaaaaa we should adjust the names for `valid_from` and `to` as well to match naming recommendations

2021-02-17 11:39 UTC, thisismana approved these changes

2021-02-17 11:44 UTC, moritzzimmer approved these changes

2021-02-17 11:44 UTC, merged