PoC: use Google API linter on GH
stroeer/tapir pull request #162
Opened 2021-02-15 13:01 UTC by moritzzimmer

2021-02-17 11:42 UTC, thisismana requested changes

2021-02-17 11:42 UTC, thisismana commented on stroeer/core/v1/article.proto
> +  google.protobuf.Timestamp valid_time = 2;
this will be fixed in #160

2021-02-17 11:42 UTC, thisismana commented on .github/workflows/pull-request.yml
> +        run: api-linter --output-format stroeer/core/v1/article.proto
section no?

2021-02-24 15:45 UTC, bobaaaaa commented
cool tool but the DX is bad :/

2021-02-26 14:22 UTC, moritzzimmer commented
@bobaaaaa @thisismana I think we can keep this tool in our toolchain (makefile, gh workflows) for (optional) linting

2021-03-01 09:37 UTC, merged