Article companions via placeholders
stroeer/tapir pull request #349
Opened 2022-02-03 15:10 UTC by harryurban

2022-02-04 10:22 UTC, harryurban commented on stroeer/fragment/v1/stage_service.proto
> +  rpc GetArticleCompanions (GetArticleCompanionsRequest) returns (GetArticleCompanionsResponse) {}
ist die Methode im StageService gut platziert? Könnte auch im ArticlePageService passen. Oder ganz woanders?

2022-02-07 10:22 UTC, moritzzimmer requested changes

2022-02-07 13:12 UTC, saefty commented on stroeer/page/article/v1/article_page.proto
> +  // contains placeholders to be replaced by paper with dynamically loaded companions
```suggestion
  // contains placeholders to be replaced with GetArticleCompanions with dynamically loaded companions
```

2022-02-07 13:12 UTC, saefty commented on stroeer/page/article/v1/article_page.proto
> +  // contains placeholders to be replaced by paper with dynamically loaded companions
Changed

2022-02-07 13:37 UTC, merged