Cleanup deprecated onwards / related_articles
stroeer/tapir pull request #526
Opened 2024-02-12 15:29 UTC by harryherbig

2024-02-12 16:08 UTC, thisismana approved these changes

2024-02-13 08:25 UTC, moritzzimmer requested changes

2024-02-13 08:25 UTC, moritzzimmer commented on stroeer/core/v1/article.proto
> -  repeated int64 onwards = 10 [deprecated = true];
we shouldn't introduce breaking changes in v1 package of core

2024-02-13 08:26 UTC, moritzzimmer requested changes

2024-02-13 08:26 UTC, moritzzimmer commented on stroeer/page/article/v1/article_page.proto
> +  reserved 2;
guess we don't need this reservation since all usages of this message are transient and we handle it internally?

2024-02-13 12:47 UTC, moritzzimmer approved these changes

2024-02-13 12:48 UTC, merged